# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rdllfdUQNUtLqzVTJF_N5RZluQZU8s6J
"""

import numpy as np

x = np.array([0, 1, 2, 3, 4, 5, 6])
y = np.array([0, 0.5, 2, 3.5, 4.5, 9, 13.5])

n = len(x)
x_mean = np.mean(x)
y_mean = np.mean(y)

m = np.sum((x - x_mean) * (y - y_mean)) / np.sum((x - x_mean)**2)
b = y_mean - m * x

y_pred = m * x + b

sy = np.sqrt(np.sum((y - y_mean)**2) / n)
syx = np.sqrt(np.sum((y - y_pred)**2) / (n - 2))
ss_total = np.sum((y - y_mean)**2)
ss_residual = np.sum((y - y_pred)**2)
r_squared = 1 - (ss_residual / ss_total)
r = np.sqrt(r_squared) * np.sign(m)

print("Desviación estándar (sy):", sy)
print("Error estándar de la estimación (syx):", syx)
print("Coeficiente de determinación (r^2):", r_squared)
print("Coeficiente de correlación (r):", r)